feat: manage hasura metadata
aura-nw/horoscope-v2 pull request #335
Opened 2023-08-22 03:06 UTC by fibonacci998

- install hasura-cli in dockerfile
- add env for hasura-cli
- add command to run hasura

2023-08-23 02:13 UTC, peara requested changes
em thêm hướng dẫn sử dụng đi

2023-08-23 02:13 UTC, peara commented on package.json
> +    "hasura:metadata:export": "touch config.yaml; hasura metadata export;rm config.yaml;",
sao phải touch rồi remove nhỉ?

2023-08-23 03:04 UTC, fibonacci998 commented on Dockerfile
> +RUN apk update && apk add bash curl && curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
done

2023-08-23 03:05 UTC, fibonacci998 commented on package.json
> +    "hasura:metadata:export": "touch config.yaml; hasura metadata export;rm config.yaml;",
hasura cli nó bắt có file config.yaml dù em đã thêm --envfile trong command của nó

2023-08-23 03:06 UTC, fibonacci998 commented
> em thêm hướng dẫn sử dụng đi

em thêm readme cho phần này rồi nhé

2023-08-23 07:02 UTC, peara commented on package.json
> +    "hasura:metadata:export": "touch config.yaml; hasura metadata export;rm config.yaml;",
nếu vậy thì em tạo 1 folder hasura rồi chạy hasura init ở đó đi, mấy cái lệnh này cho cd vào  folder đó chạy

2023-08-23 07:04 UTC, peara commented on package.json
> +    "hasura:metadata:export": "touch config.yaml; hasura metadata export;rm config.yaml;",
anh vừa thử hasura init thì nó bảo tạo folder hasura luôn, rồi vào đó chạy tiếp

2023-08-23 09:07 UTC, fibonacci998 commented on package.json
> +    "hasura:metadata:export": "touch config.yaml; hasura metadata export;rm config.yaml;",
em bỏ hết mấy lệnh viết thêm trong package.json rồi, dùng luôn command hasura cho tiện vậy

2023-09-05 03:21 UTC, peara commented on Dockerfile
> +FROM node:16
chỗ này để alpine ko chạy được à?
vậy nên tạo 1 image riêng cho cái hasura này thôi

2023-09-05 03:29 UTC, fibonacci998 commented on Dockerfile
> +FROM node:16
dùng image nào cho nhẹ anh nhỉ?

2023-09-05 09:43 UTC, fibonacci998 commented on Dockerfile
> +FROM node:16
em tạo cho hasura 1 dockerfile dùng node16 rồi nhé

2023-09-05 09:48 UTC, fibonacci998 commented on Dockerfile
> +FROM node:16
ơ mà cách này thì lúc nào chạy docker build cũng phải build lại cả 2 image rồi push lên hả anh?

2024-01-05 09:31 UTC, closed without merging