refactor: cw721 media checkpoint for token
aura-nw/horoscope-v2 pull request #660
Opened 2024-02-23 08:01 UTC by phamphong9981

2024-02-23 09:43 UTC, peara requested changes

2024-02-23 09:43 UTC, peara commented on src/services/cw721/cw721-media.service.ts
> +      .andWhere('id', '>', idTokenCheckpoint)
thêm `asc` vào orderBy cho chắc

2024-02-23 09:43 UTC, peara commented on src/services/cw721/cw721-media.service.ts
> +              removeOnFail: false,
sao lại sửa cái này?

2024-02-23 09:43 UTC, peara commented on src/services/cw721/cw721-media.service.ts
> +      await BlockCheckpoint.query().insert({
transaction đâu

2024-02-26 02:14 UTC, phamphong9981 commented on src/services/cw721/cw721-media.service.ts
> +      await BlockCheckpoint.query().insert({
Em thấy hàm này có 1 insert nên ko cho vào transaction. Các hàm khác gọi thông qua queue

2024-02-26 02:35 UTC, peara commented on src/services/cw721/cw721-media.service.ts
> +      await BlockCheckpoint.query().insert({
ok

2024-02-26 02:37 UTC, peara approved these changes

2024-02-26 02:38 UTC, merged